# Generated by Django 3.2.8 on 2021-10-25 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='Main operation identification', primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(null=True)),
                ('created', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Balance after current transaction', max_digits=10)),
                ('kind', models.CharField(choices=[('PURCHASE', 'Transaction:Purchase (positive)'), ('REFUND', 'Transaction:Refund (negative)'), ('WITHDRAWAL', 'Withdrawal (negative)')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
